import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Discord",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="h-screen flex justify-center items-center bg-black overflow-hidden">
      {children}
    </div>
  );
}
